export enum StudyPlanStatus {
  IN_DEVELOPMENT = 'IN_DEVELOPMENT',
  TO_REFACTOR = 'TO_REFACTOR',
  TO_REGISTER = 'TO_REGISTER',
  REFACTORED = 'REFACTORED',
  REGISTERED = 'REGISTERED',
  SUBMITTED = 'SUBMITTED'
}
