export enum DisciplineType {
  STANDARD = 'STANDARD',
  BASIC = 'BASIC',
  EXTRA = 'EXTRA',
  PRACTICE = 'PRACTICE',
  FACULTATIVE = 'FACULTATIVE',
  COURSE_WORK = 'COURSE_WORK',
  COURSE_PROJECT = 'COURSE_PROJECT'
}
