export enum CycleType {
  STANDARD = 'STANDARD',
  BASIC = 'BASIC',
  COURSE = 'COURSE',
  EXTRA = 'EXTRA',
  FACULTATIVE = 'FACULTATIVE',
  PRACTICE = 'PRACTICE',
  DIPLOMA_DESIGN = 'DIPLOMA_DESIGN',
  FINAL_EXAMINATION = 'FINAL_EXAMINATION'
}
